### ISSUE TITLE
Any.Do Alternative

### ISSUE THREAD

**Issue by briant97** [pilotmoon/PopClip-Extensions#1007] opened 2017-09-29 14:36 UTC
With Wunderlist being shutdown in the near future can you setup Any.Do as an alternative please.  I would like to label this as an idea but can't find out where to do that.

**Comment by invariant** [comment] 2017-10-01 15:42
Thanks Brian! Dupe of #454, closing and adding reference to that issue.

**Closed by invariant** 2017-10-01 15:42 UTC
