### ISSUE TITLE
Reminders.popclipextz doesn't work

### ISSUE THREAD

**Issue by YELLOWHOMEIN** [pilotmoon/PopClip-Extensions#1121] opened 2020-02-09 01:28 UTC
the reminder app can be evoke, but it can't not add a new reminders.  How to fix it？

**Comment by stevenrasz** [comment] 2020-07-22 05:26
I had trouble with this one too. Instead, I created a shell script extension with the following code to run AppleScript from there.

`osascript -e \
'on run {myinput}
	tell application "Reminders"
		activate
		set myReminder to (make new reminder with properties {name:myinput})
		show myReminder
	end tell
end run' "$POPCLIP_TEXT"`

**Comment by invariant** [comment] 2020-10-21 20:16
Closing this one - kind of dupe of #793 
The old Reminders extension stopped working. I need to do a new one.
Thanks for code snippet, @audero-cmyk

**Closed by invariant** 2020-10-21 20:16 UTC
